### ISSUE TITLE
Running bot headless ends in infinite loop

### ISSUE THREAD

**Issue by jankornfeld** [Bettehem/ts3-musicbot#6]
Hi there,
When I try to start the bot headless it starts with:
![image](https://github.com/Bettehem/ts3-musicbot/assets/22515470/67662f0f-5145-4326-bcf6-d89fc80dc813)

then it's spaming the following:
![image](https://github.com/Bettehem/ts3-musicbot/assets/22515470/ad77c40f-eb06-4633-8c38-ed520869a2e0)

Do I miss something? I was just following the Installation guide from the wiki.

Also the config which it is trying to access at the beginning of the command is not created. Do I need to create it myself?

BR
Jan

**Comment by Bettehem** [comment]
Hello, thanks for the issue report. I would need a bit more information though.
What OS are you using and were you able to successfully install all the dependencies?
You don't necessarily need to manually create the config file, you have a few options for that as explained here in the wiki:
https://gitlab.com/Bettehem/ts3-musicbot/-/wikis/installation#running-the-bot (click on `Show creating a config file`)
Based on your second screenshot, it seems like you possibly created an empty config file or at least one with no server address?

For future issues, I would recommend creating them on the project's GitLab page as this GitHub page is only a mirror and on GitLab is the project's main page.
Here's a link to the GitLab issue page: https://gitlab.com/Bettehem/ts3-musicbot/-/issues

**Comment by jankornfeld** [comment]
Updated and moved to GitLab https://gitlab.com/Bettehem/ts3-musicbot/-/issues/23
