### ISSUE TITLE
Move bot to room using commands?

### ISSUE THREAD

**Issue by PatRakowicz** [Bettehem/ts3-musicbot#9]
Hello, was wondering if there is a way to get the bot to move to a room when a user requests the bot to move? Would something else be needed for the teamspeak client to allow this to be done?

For example, if a user is in a different room and the bot is in a place holder room, if the user requests the bot `%come` the bot moves to the room and when the user is done using the bot `%goaway` the bot goes back to the place holder room.

**Comment by Bettehem** [comment]
Hello, currently there is no way of joining a specific channel using the chat commands, but you can set a specific channel to join in the bot's config file with the `CHANNEL_NAME` config option, or using the `-c`/`--channelname` flag when launching the bot.

I could add a chat command for joining a different channel. How does something like `%goto` and `%return` sound?
The syntax to join a channel named "somechannel" could be something like this: `%goto somechannel`
And when you want the bot to return to the original channel, you would run the `%return` command.

Let me know if you think this is good or if something should be changed

**Comment by PatRakowicz** [comment]
Yea that would work. Either that or allow the user to direct message the bot, asking to `%join` allowing the bot to join the channel the user is in. Or allowing to directly have the bot go to a channel as mentioned above.

**Comment by Bettehem** [comment]
Added `%goto` and `%return` commands in the latest commit: [fed126ca](https://github.com/Bettehem/ts3-musicbot/commit/fed126ca8ceb31ec6da694f4dc32452fad28eb57)
